apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c3agj1zvi-go 
  janus-idp.io/tekton: c3agj1zvi-go
  backstage.io/kubernetes-id: c3agj1zvi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c3agj1zvi-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml