apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c3agj1zvi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c3agj1zvi-go 
  name: c3agj1zvi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c3agj1zvi-go 
